const en = {
  about: {
    title: "Ayoub METWALLI",
    logo: "AyoubMetwalli",
    website: "https://ayoubmetwalli.com/",
    subtitle: [
      "Technical Leader, Full Stack Developer & Technology Enthusiast.",
    ],
    resume: "./Ayoub_Metwalli_resume.pdf",
    picture: "./user.jfif",
    about: [
      "At the tender age of 11, I received my first PC, only to break it within a few days.",
      "After a few weeks, I stumbled upon some PHP scripts, despite having no prior knowledge of what they were.",
      "Intrigued, I sought out tutorials on how to use and install these scripts on free hosting platforms.",
      "This marked the beginning of my exploration into the world of coding and web development.",
      'My initial triumph? Creating my first website that proudly displayed a "Hello World" message—best viewed on Internet Explorer, of course.',
      "Determined to expand my skills, I delved into learning HTML, enabling me to craft simple websites and tweak existing scripts.",
      "Fast forward to today, and I proudly serve as the head of Qodly's Customer Success team—a testament to the journey that began with a curious exploration of PHP scripts.",
    ],
  },
  seo: {
    title: "Ayoub METWALLI's Portfolio",
    description:
      "Technical Leader, Full Stack Developer & Technology Enthusiast",
    og: {
      title: "Ayoub METWALLI Portfolio",
      type: "website",
      url: "https://ayoubmetwalli.com/",
      description:
        "Technical Leader, Full Stack Developer & Technology Enthusiast",
      site_name: "Ayoub METWALLI",
    },
  },
  footer: {
    title: "Ayoub Metwalli",
    linkedin: "https://www.linkedin.com/in/ayoubmetwalli/",
    github: "https://github.com/metayoub/",
    facebook: "https://www.facebook.com/yb.metwalli/",
    instagram: "https://www.instagram.com/ayoub_met/",
  },
  experience: [
    {
      id: 1,
      role: "Head of Qodly's Customer Success team",
      year: "Since 09/2023",
      location: "Rabat/ Morocco",
      company: "4D Maroc",
      description: [
        "Analyze clients needs and find solutions to serve them.",
        "Check that applications are updated and the code is clean and good.",
        "Train and help technical personnel.",
        "Guide the Devs through technical issues and challenges.",
        "Help hirring technical personnel.",
        "Identify areas of improvement.",
        "Resolve high priority issues.",
        "Search new technologies, tools and concepts.",
        "Customize solutions and improve business processes, operations and profitability.",
      ],
    },
    {
      id: 2,
      role: "Technical lead",
      year: "From 07/2021 To 09/2023",
      location: "Rabat/ Morocco",
      company: "4D Maroc",
      description: [
        "Analyze clients needs and find solutions to serve them.",
        "Check that applications are updated and the code is clean and good.",
        "Train and help technical personnel.",
        "Guide the Devs through technical issues and challenges.",
        "Help hirring technical personnel.",
        "Identify areas of improvement.",
        "Resolve high priority issues.",
        "Search new technologies, tools and concepts.",
        "Customize solutions and improve business processes, operations and profitability.",
      ],
    },
    {
      id: 3,
      role: "Software engineer",
      year: "From 01/2019 to 04/2021",
      location: "Paris/ France",
      company: "4D /  Malakoff Humanis",
      description: [
        "Contributor of a ten-member agile team for an assurance product application.",
        "Developed additional features using 4D, JAVA and Angular.",
        "Wrote data processing batchs in 4D.",
        "Followed Scrum/Agile methodology with daily meetings to keep track of the progress and issues pertaining to the projects.",
        "Resolved high priority production issues.",
      ],
    },
    {
      id: 4,
      role: "Full Stack Developer",
      year: "From 11/2016 to 06/2021",
      location: "Rabat/ Moroccoo",
      company: "4D Maroc",
      description: [
        "Well-versed in all phases in all phases of Software Development Lifecycle includingAnalysis, Design, Coding, Debugging, Testing with good knowledge of Data structure and Algorithms.",
        "Developed back-end web applications and APIs using 4D.",
        "Developed dynamic front-end applications using Angular or React.",
        "Developed custom Docker images for test automation integration.",
        "Developed Shell Scripts to automate repeated manual steps for different data setups and deployments.",
        "Consumed web APIs from third-party sites like AzureCloud, GoogleMaps.",
        "Proven success engineering customized solutions improving business processes, operations and profitability.",
      ],
    },
  ],
  education: [
    {
      id: 1,
      diploma: " MSc Durable Financial engineering and Risk management",
      school: "High National School for Computer Science and Systems Analysis",
      where: "Rabat/ Morocco",
      year: "From September 2017 to July 2020",
      keys: "Pricing, Financial Modeling, Financial Risk, Derivative (Finance), Financial Engineering, Real Options Valuation, Risk Management",
    },
    {
      id: 2,
      diploma: "Computer engineering",
      school: "High National School for Computer Science and Systems Analysis",
      where: "Rabat/ Morocco",
      year: "From September 2013 to July 2016",
      keys: "Software engineering, Data Structures, Web Application Architecture, Algorithms, Parallel Programming, DataBase, Modern Programming Practice, Computer Science",
    },
    {
      id: 3,
      diploma: "Higher School Preparatory Classes",
      school: "CPGE Moulay Abdellah",
      where: "Safi / Morocco",
      year: "From September 2011 to Mai 2013",
      keys: 'Two-year highly selective classes to prepare for the competitive exams to the "Grandes Ecoles"',
    },
  ],
  skill: [
    "4D",
    "Javascript",
    "TypeScript",
    "NodeJs",
    "ReactJS",
    "Go",
    "C",
    "C++",
    "Docker",
    "Git",
    "CI/CD",
    "Rest",
    "GraphQL",
    "Elastic",
    "Logstash",
    "Jest",
    "Junit",
    "MySQL",
    "MongoDB",
  ],
};

export { en };
